### ISSUE TITLE
LTCPacket.asByteArray() is empty

### ISSUE THREAD

**Issue by aillience** [MrExplode/ltc4j#5]
Hello, I use LTCPacket like this:
`LTCPacket packet = new LTCPacket(0,1,2,20,Framerate.FRAMERATE_25); byte[] data = packet.asByteArray();`
but when I print data,The array is [0,0,.....0].Why?

**Comment by MrExplode** [comment]
Hello!
Unfortunately I don't know. This project was left unfinished a long time ago and I don't have time and/or motivation to catch up with the code and make it usable. You may have success with using [libltc](https://github.com/x42/libltc) with JNI, [JNA](https://github.com/java-native-access/jna) or java FFI (still in incubator)
My attempt at using it with JNI: [1](https://github.com/MrExplode/ShowManager/blob/master/core/src/main/java/me/sunstorm/showmanager/ltc/LibLTCWrapper.java), [2](https://github.com/MrExplode/ShowManager/blob/master/libltc/libltc/Dll1/me_sunstorm_showmanager_ltc_LibLTCWrapper.cpp)
Unfortunately due to a tight deadline I had to abandon the LTC generation in that project, and fell back to just [playing](https://github.com/MrExplode/ShowManager/blob/7c2e624f3eadc4a4b0ec0d13d3cf17aff4bb21c2/core/src/main/java/me/sunstorm/showmanager/ltc/LtcHandler.java#L42) a pregenerated wav file

**Comment by aillience** [comment]
Okay， I think I can handle it！Thanks anyway
